"""Initial Migration

Revision ID: 6a73779fd03e
Revises: 23f16d70227c
Create Date: 2019-03-01 10:32:39.852281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a73779fd03e'
down_revision = '23f16d70227c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(length=240), autoincrement=False, nullable=True))
    op.drop_column('comments', 'posted')
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
